# Generated by Django 5.0 on 2023-12-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('instructor', models.CharField(max_length=100)),
                ('course_length', models.CharField(max_length=100)),
            ],
        ),
    ]
